# The services of the project.
# ... comments ...

services:          # <-- Add this top-level key
  db:              # <-- Indent this and everything below it
      type: postgresql:12
      disk: 256
  # Alternative database options
  # MySQL/MariaDB database service.
  # db:
  #     type: mariadb:10.5
  #     disk: 256
  # Redis caching service.
  cacheredis:
      type: redis:6.0
  # Redis rate-limiting service.
  ratelimitredis:
      type: redis:6.0