# The services of the project.

services:
  db:
      type: postgresql:12
  # We removed the 'disk: 256' line from here

  # Redis caching service.
  cacheredis:
      type: redis:6.0

  # Redis rate-limiting service.
  ratelimitredis:
      type: redis:6.0